// Mock data for WE4FREE Lattice Deck
import type {
  LaneStatus, ControlPlaneStatus, SurfaceCell, TimelineEvent,
  MessagePacket, ContinuityState
} from './types';

export const mockLaneStatuses: LaneStatus[] = [
  {
    id: 'archivist',
    name: 'Archivist',
    status: 'active',
    currentTask: 'Ingesting artifact batch #2847 — verifying checksums',
    lastHeartbeat: '2026-05-14T08:12:33Z',
    lastCommit: 'a3f8c2e (3h ago)',
    lastCompact: '2026-05-14T04:00:00Z',
    lastRestore: '2026-05-13T22:15:00Z',
    lastTestResult: 'pass',
    gitBranch: 'main',
    gitAhead: 2,
    gitBehind: 0,
    driftWarning: false,
    blockerCount: 0,
    activeSurfaces: ['desktop', 'headless'],
    currentAgent: 'archivist-agent-v3',
    currentModel: 'claude-sonnet-4-20250514',
    contextPercent: 87.3,
    compactCount: 1247,
    lastHandoffPacket: 'pkt-a3f8c2e-001',
  },
  {
    id: 'library',
    name: 'Library',
    status: 'blocked',
    currentTask: 'Graph index scope explosion — under investigation',
    lastHeartbeat: '2026-05-14T07:45:10Z',
    lastCommit: 'b71d4f0 (1d ago)',
    lastCompact: '2026-05-14T03:30:00Z',
    lastRestore: '2026-05-13T21:45:00Z',
    lastTestResult: 'fail',
    gitBranch: 'feat/graph-index-scope',
    gitAhead: 5,
    gitBehind: 3,
    driftWarning: true,
    blockerCount: 2,
    activeSurfaces: ['headless', 'gastown'],
    currentAgent: 'library-agent-v3',
    currentModel: 'claude-sonnet-4-20250514',
    contextPercent: 94.1,
    compactCount: 892,
    lastHandoffPacket: 'pkt-b71d4f0-017',
  },
  {
    id: 'swarmmind',
    name: 'SwarmMind',
    status: 'active',
    currentTask: 'Lane loop iteration #139 — sovereignty check',
    lastHeartbeat: '2026-05-14T08:10:05Z',
    lastCommit: 'e90aa31 (5h ago)',
    lastCompact: null,
    lastRestore: null,
    lastTestResult: 'pass',
    gitBranch: 'main',
    gitAhead: 0,
    gitBehind: 1,
    driftWarning: false,
    blockerCount: 0,
    activeSurfaces: ['headless'],
    currentAgent: 'swarm-agent-v2',
    currentModel: 'claude-sonnet-4-20250514',
    contextPercent: 97.0,
    compactCount: 0,
    lastHandoffPacket: 'pkt-e90aa31-003',
  },
  {
    id: 'kernel',
    name: 'Kernel',
    status: 'active',
    currentTask: 'Lane loop — monitoring health signals',
    lastHeartbeat: '2026-05-14T08:11:58Z',
    lastCommit: 'c4d5e6f (6h ago)',
    lastCompact: null,
    lastRestore: null,
    lastTestResult: 'pass',
    gitBranch: 'main',
    gitAhead: 1,
    gitBehind: 0,
    driftWarning: false,
    blockerCount: 0,
    activeSurfaces: ['headless'],
    currentAgent: 'kernel-agent-v1',
    currentModel: 'claude-sonnet-4-20250514',
    contextPercent: 99.2,
    compactCount: 0,
    lastHandoffPacket: 'pkt-c4d5e6f-001',
  },
];

export const mockControlPlane: ControlPlaneStatus = {
  id: 'control-plane',
  name: 'Control Plane',
  status: 'active',
  currentTask: 'Rig coordination — 4 lanes supervised',
  lastHeartbeat: '2026-05-14T08:12:00Z',
  coordinatorVersion: 'v2.4.1',
  activeLanes: ['archivist', 'library', 'swarmmind', 'kernel'],
  messageQueueDepth: 3,
  pendingDecisions: 1,
  gitBranch: 'main',
  gitAhead: 0,
  gitBehind: 2,
};

export const surfaceMatrix: SurfaceCell[][] = [
  [
    { laneId: 'archivist', surfaceId: 'desktop', state: 'supervising', label: 'Supervising', repo: 'we4free/archivist', branch: 'main', lastChange: '2026-05-14T06:30:00Z', agent: 'archivist-agent-v3', logs: ['[08:12] Heartbeat OK', '[07:45] Compact #1247 done', '[06:30] Watchdog sync'] },
    { laneId: 'archivist', surfaceId: 'headless', state: 'executing', label: 'Executing', repo: 'we4free/archivist', branch: 'main', lastChange: '2026-05-14T04:00:00Z', agent: 'archivist-agent-v3', logs: ['[08:10] CI push success', '[04:00] Compact/restore cycle complete', '[03:30] Auto-save checkpoint'] },
    { laneId: 'archivist', surfaceId: 'gastown', state: 'none', label: 'None', repo: '—', branch: '—', lastChange: null, agent: null, logs: [] },
    { laneId: 'archivist', surfaceId: 'vps', state: 'none', label: 'None', repo: '—', branch: '—', lastChange: null, agent: null, logs: [] },
  ],
  [
    { laneId: 'library', surfaceId: 'desktop', state: 'wip', label: 'Local WIP', repo: 'we4free/library', branch: 'feat/graph-index-scope', lastChange: '2026-05-14T07:00:00Z', agent: null, logs: ['[07:00] Manual edit: scope resolver', '[06:45] Debug session started'] },
    { laneId: 'library', surfaceId: 'headless', state: 'executing', label: 'CI Loop', repo: 'we4free/library', branch: 'feat/graph-index-scope', lastChange: '2026-05-14T07:45:00Z', agent: 'library-agent-v3', logs: ['[07:45] Cycle 139 sovereignty FAIL', '[07:30] Graph scope exception', '[06:00] Cycle 138 PASS'] },
    { laneId: 'library', surfaceId: 'gastown', state: 'coordinating', label: 'Mayor Aware', repo: 'we4free/library', branch: 'main', lastChange: '2026-05-13T20:00:00Z', agent: 'mayor-proxy', logs: ['[20:00] Sovereign report received', '[19:00] Municipal check OK'] },
    { laneId: 'library', surfaceId: 'vps', state: 'none', label: 'None', repo: '—', branch: '—', lastChange: null, agent: null, logs: [] },
  ],
  [
    { laneId: 'swarmmind', surfaceId: 'desktop', state: 'none', label: 'None', repo: '—', branch: '—', lastChange: null, agent: null, logs: [] },
    { laneId: 'swarmmind', surfaceId: 'headless', state: 'executing', label: 'Lane Loop', repo: 'we4free/swarmmind', branch: 'main', lastChange: '2026-05-14T05:00:00Z', agent: 'swarm-agent-v2', logs: ['[08:10] Iteration 139 start', '[05:00] Iteration 138 complete', '[05:00] Sovereignty: PASS'] },
    { laneId: 'swarmmind', surfaceId: 'gastown', state: 'none', label: 'None', repo: '—', branch: '—', lastChange: null, agent: null, logs: [] },
    { laneId: 'swarmmind', surfaceId: 'vps', state: 'none', label: 'None', repo: '—', branch: '—', lastChange: null, agent: null, logs: [] },
  ],
  [
    { laneId: 'kernel', surfaceId: 'desktop', state: 'none', label: 'None', repo: '—', branch: '—', lastChange: null, agent: null, logs: [] },
    { laneId: 'kernel', surfaceId: 'headless', state: 'executing', label: 'Lane Loop', repo: 'we4free/kernel', branch: 'main', lastChange: '2026-05-14T06:00:00Z', agent: 'kernel-agent-v1', logs: ['[08:11] Health signal OK', '[06:00] Lane sync complete', '[06:00] Integrity: GREEN'] },
    { laneId: 'kernel', surfaceId: 'gastown', state: 'none', label: 'None', repo: '—', branch: '—', lastChange: null, agent: null, logs: [] },
    { laneId: 'kernel', surfaceId: 'vps', state: 'none', label: 'None', repo: '—', branch: '—', lastChange: null, agent: null, logs: [] },
  ],
];

export const mockTimeline: any[] = [
  { id: 'e1', timestamp: '2026-05-14T08:12:00Z', laneId: 'archivist', surfaceId: 'headless', type: 'REPAIR', title: 'Recovery snapshot regenerated', description: '12/12 PASS — all integrity checks passed', artifactPath: '/artifacts/archivist/snapshot-20260514-0812', gitRef: 'a3f8c2e', attribution: 'archivist-agent-v3', classification: 'autonomous' },
  { id: 'e2', timestamp: '2026-05-14T07:45:00Z', laneId: 'library', surfaceId: 'headless', type: 'REGRESSION', title: 'CI push failures begin', description: 'Failures every ~4 min — graph scope index overflow', artifactPath: '/artifacts/library/ci-log-20260514-0745', gitRef: 'b71d4f0', attribution: 'library-agent-v3', classification: 'autonomous' },
  { id: 'e3', timestamp: '2026-05-14T07:30:00Z', laneId: 'library', surfaceId: 'headless', type: 'RECONCILIATION', title: 'Sovereignty check cycle 139', description: 'Graph index scope mismatch detected', artifactPath: null, gitRef: 'b71d4f0', attribution: 'library-agent-v3', classification: 'autonomous' },
  { id: 'e4', timestamp: '2026-05-14T05:00:00Z', laneId: 'swarmmind', surfaceId: 'headless', type: 'PROGRESSION', title: 'Lane loop iteration 139 complete', description: 'Sovereignty PASS — all sub-agents aligned', artifactPath: '/artifacts/swarmmind/iteration-139', gitRef: 'e90aa31', attribution: 'swarm-agent-v2', classification: 'autonomous' },
  { id: 'e5', timestamp: '2026-05-14T04:00:00Z', laneId: 'archivist', surfaceId: 'headless', type: 'INFRASTRUCTURE', title: 'Compact/restore cycle complete', description: 'Cycle #1247 — 96.8% fidelity', artifactPath: '/artifacts/archivist/compact-1247', gitRef: 'a3f8c2e', attribution: 'archivist-agent-v3', classification: 'autonomous' },
  { id: 'e6', timestamp: '2026-05-14T03:30:00Z', laneId: 'library', surfaceId: 'desktop', type: 'UNDO', title: 'Scope resolver edit reverted', description: 'Manual WIP change reverted — conflict with headless branch', artifactPath: null, gitRef: 'b71d4f0~1', attribution: 'operator', classification: 'operator' },
  { id: 'e7', timestamp: '2026-05-14T03:00:00Z', laneId: 'kernel', surfaceId: 'headless', type: 'PROGRESSION', title: 'Health signal baseline updated', description: 'All lanes reporting normally', artifactPath: '/artifacts/kernel/health-20260514', gitRef: 'c4d5e6f', attribution: 'kernel-agent-v1', classification: 'autonomous' },
  { id: 'e8', timestamp: '2026-05-14T02:15:00Z', laneId: 'archivist', surfaceId: 'headless', type: 'REPAIR', title: 'Block chain verification repaired', description: 'Minor corruption in block 2846 auto-repaired', artifactPath: '/artifacts/archivist/repair-2846', gitRef: 'a3f8c2d', attribution: 'archivist-agent-v3', classification: 'autonomous' },
  { id: 'e9', timestamp: '2026-05-14T01:00:00Z', laneId: 'control-plane', surfaceId: 'desktop', type: 'INFRASTRUCTURE', title: 'Rig coordination update v2.4.1', description: 'Coordination protocol updated', artifactPath: '/artifacts/control-plane/coord-v2.4.1', gitRef: 'cp-2.4.1', attribution: 'operator', classification: 'operator' },
  { id: 'e10', timestamp: '2026-05-13T22:15:00Z', laneId: 'archivist', surfaceId: 'desktop', type: 'RECONCILIATION', title: 'Restore gate comparison', description: 'Desktop ↔ Headless reconciliation — 97.2% match', artifactPath: null, gitRef: 'a3f8c2c', attribution: 'archivist-agent-v3', classification: 'autonomous' },
  { id: 'e11', timestamp: '2026-05-13T20:00:00Z', laneId: 'library', surfaceId: 'gastown', type: 'PROGRESSION', title: 'Sovereignty reported to Mayor', description: 'Library status confirmed via Gastown channel', artifactPath: null, gitRef: 'b71d4e0', attribution: 'mayor-proxy', classification: 'autonomous' },
  { id: 'e12', timestamp: '2026-05-13T16:03:00Z', laneId: 'archivist', surfaceId: 'headless', type: 'PROGRESSION', title: 'Added archivist to continuous-improvement loop', description: 'Self-improvement cycle enabled', artifactPath: '/artifacts/archivist/ciloop-config', gitRef: 'a3f8c2b', attribution: 'archivist-agent-v3', classification: 'autonomous' },
  { id: 'e13', timestamp: '2026-05-13T12:22:00Z', laneId: 'library', surfaceId: 'headless', type: 'PROGRESSION', title: 'Cycle 139 sovereignty PASS', description: 'Graph index integrity verified', artifactPath: '/artifacts/library/sovereignty-139', gitRef: 'b71d4e0', attribution: 'library-agent-v3', classification: 'autonomous' },
  { id: 'e14', timestamp: '2026-05-13T10:40:00Z', laneId: 'archivist', surfaceId: 'headless', type: 'REGRESSION', title: 'CI push failures begin', description: 'Pushing every ~4 min', artifactPath: '/artifacts/archivist/ci-failures-20260513', gitRef: 'a3f8c28', attribution: 'archivist-agent-v3', classification: 'autonomous' },
];

export const mockMessages: MessagePacket[] = [
  { id: 'm1', to: 'lanes/archivist/inbox', priority: 'high', type: 'action-required', requiresAction: true, body: 'Review the last 48 hours of changes. Classify progression/regression/overwrite/duplicate work. Do not mutate code. Return a timestamped audit.', createdAt: '2026-05-14T07:00:00Z', sentAt: '2026-05-14T07:01:00Z', delivered: true, read: true, acknowledged: true, actionStarted: true, resultArtifact: '/artifacts/archivist/audit-20260514', recipients: [{ entityId: 'archivist' }] },
  { id: 'm2', to: 'lanes/library/inbox', priority: 'normal', type: 'informational', requiresAction: false, body: 'Sovereignty check completed. Graph index scope under investigation.', createdAt: '2026-05-14T06:00:00Z', sentAt: '2026-05-14T06:01:00Z', delivered: true, read: true, acknowledged: false, actionStarted: false, resultArtifact: null, recipients: [{ entityId: 'library' }] },
];

export const mockContinuity: ContinuityState[] = [
  { laneId: 'archivist', currentStep: 'SYNC', passRate: 96.8, status: 'green', lastUpdated: '2026-05-14T04:00:00Z', details: 'Last compact/restore: 96.8% fidelity. All checks passed.' },
  { laneId: 'library', currentStep: 'QUARANTINE', passRate: 88.2, status: 'red', lastUpdated: '2026-05-14T07:45:00Z', details: 'Compact restore comparison = 88.2%. UNBLOCK DENIED.' },
  { laneId: 'swarmmind', currentStep: 'UNBLOCK', passRate: 97.0, status: 'green', lastUpdated: '2026-05-14T05:00:00Z', details: 'Iteration 139 sovereignty PASS.' },
  { laneId: 'kernel', currentStep: 'UNBLOCK', passRate: 99.2, status: 'green', lastUpdated: '2026-05-14T06:00:00Z', details: 'Health signal OK. Integrity: GREEN.' },
  { laneId: 'control-plane', currentStep: 'SYNC', passRate: 95.5, status: 'green', lastUpdated: '2026-05-14T08:12:00Z', details: 'Rig coordination active. 4 lanes supervised.' },
];